### PR TITLE
Fix/prettier

### PR DESCRIPTION
**Pull request by dantxal**
# Summary

This PR intends to solve the issue we are having with CI when it runs the 'Format' action.
We are now passing a path to the files and have a configuration file that corresponds to the way we had been formatting the majority of the code.

## Test Plan

So far, manually running `yarn prettier **/src/**/*.(ts|tsx)` at root folder is working. We need to test wether that will work on the CI.

### CODE REVIEW

**Review by sibelius — APPROVED** [review]
Awesome 

Tks

**Comment by dantxal** [comment]
A action Format passou, mais o comando lint nao existe.

Qual seria esse comando lint no caso?

**Comment by sibelius** [comment]
lint should call `eslint`

**Comment by sibelius** [comment]
prettier is great

**Pull request merged**
